services:
  db:
    image: postgres:16
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=local
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local
